name: My First CI

on:
  push:
  workflow_dispatch:

jobs:
  test-allmost-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Show files
        run: ls -la
      - name: setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check Java version
        run: java -version
      - name: Download dependencies
        run: mvn dependency:resolve
      - name: Create a project buid
        run: mvn clean package
      - name: Run unit tests
        run: mvn test
